version: '3.5'

services:

  docker_kubernetes_example_a_webfront:
    container_name: web_front_type_a
    build:
      context: ./web_front
      dockerfile: Dockerfile
    environment:
      API_SERVER_HOSTNAME: api_server_type_a
      API_SERVER_PROTOCOL: http
      API_SERVER_PORT: 8081
    ports:
      - "8080:8080"
    restart: always

  docker_kubernetes_example_a_apiserver:
    container_name: api_server_type_a
    build:
      context: ./api_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql_server
    environment:
      DATABASE_HOST: mysql_server
      DATABASE_PORT: 3306
      DATABASE_NAME: docker_kubernetes_example_type_a
      DATABASE_USER: type_a
      DATABASE_PASSWD: abcde12345
    restart: always

  mysql_server:
    container_name: mysql_server
    build:
      context: ./mysql_server
      dockerfile: Dockerfile


