version: '3.5'

services:

  docker_kubernetes_example-a-webfront:
    container_name: web-front_type_a
    build:
      context: ./web_front
      dockerfile: Dockerfile
    environment:
      API_SERVER_HOSTNAME: api-server_type_a
      API_SERVER_PROTOCOL: http
      API_SERVER_PORT: 8081
    ports:
      - "8080:8080"
    restart: always

  docker_kubernetes_example-a-apiserver:
    container_name: api-server_type_a
    build:
      context: ./api_server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

