version: '3.5'

services:

  docker_kubernetes_example_a_webfront:
    container_name: web_front_type_a
    build:
      context: ./web_front
      dockerfile: Dockerfile
    environment:
      SELF_PORT: 8080
      SELF_IP: 0.0.0.0
      API_SERVER: http://api_server_type_a:8081
      API_SERVER_HOSTNAME: api_server_type_a
      API_SERVER_PROTOCOL: http
      API_SERVER_PORT: 8081
    ports:
      - 8080:8080
    depends_on:
      - docker_kubernetes_example_a_apiserver
    restart: always

  docker_kubernetes_example_a_apiserver:
    container_name: api_server_type_a
    build:
      context: ./api_server
      dockerfile: Dockerfile
    environment:
      SELF_PORT: 8081
      SELF_IP: 0.0.0.0
      DATABASE_HOST: mysql_server_type_a
      DATABASE_PORT: 3306
      DATABASE_NAME: docker_kubernetes_example_type_a
      DATABASE_USER: type_a
      DATABASE_PASSWD: abcde12345type_a
    ports:
      - 8081:8081
    depends_on:
      - mysql_server
    restart: always

  mysql_server:
    container_name: mysql_server_type_a
    build:
      context: ./mysql_server
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: abcde12345root
      MYSQL_DATABASE: docker_kubernetes_example_type_a
      MYSQL_USER: type_a
      MYSQL_PASSWORD: abcde12345type_a
    restart: always


